version: "3.0"
services:
  rasa:
    image: rasa/rasa:2.0.6-full
    ports:
      - 5005:5005
    volumes:
      - ./rasa:/app
    command: ["run", "--cors", "*"]

  actions:
    build:
      context: .
      dockerfile: ./rasa/Dockerfile
    image: milo-action
    ports:
      - 5055:5055

  knowledge_base:
    build:
      context: .
      dockerfile: ./db/Dockerfile
    ports:
      # Temporarily changed local port to avoid conflicts.
      - 65432:5432
    restart: always
    environment:
      - POSTGRES_DBNAME=knowledgebase
      - POSTGRES_USER=kbadmin
      - POSTGRES_PASSWORD=knowledgebase

networks:
  default:
    external:
      name: interpreter_net
